name: "Tests"
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.8]

    steps:
      - uses: actions/checkout@v2
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: run-tests
        run: |
          python -m unittest
